### ISSUE TITLE
Introduce CAC

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/changelogen#109]
### Describe the feature

Hello,

In order to easily add new command and understand how the CLI works (because there is more and more feature), I think that we could use a tool like CAC, https://github.com/cacjs/cac, to achieve this.

Currently, there is no `-h` flag and there is many more flag to come.

https://github.com/unjs/changelogen/issues/104 with a `--prevenance`
https://github.com/unjs/changelogen/issues/105 with a `--publish`
https://github.com/nuxt/nuxt/issues/20675 with a flag to create a PR (where we could personalize changelog header)

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hey :) Our CLI is powered by [unjs/citty](https://github.com/unjs/citty). Check `src/cli.ts` and `src/command`. For now args are not documented (because of backward compatibility) but once we add meta, `--help` will show them..

**Comment by Barbapapazes** [comment]
Sorry to ask but I dit not find any  `unjs/citty` in the repo? 🤷‍♂️
