### ISSUE TITLE
Docs: example of how to create version like "v1.0.0-beta.0"

### ISSUE THREAD

**Issue by kylegl** [unjs/changelogen#150]
### Describe the feature

For example, lets say I'm currently on `v0.9.0` and i want to bump it to `v1.0.0-beta.0`. How can I accomplish this?

Thanks!

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by JohnCampionJr** [comment]
Just had to figure this out myself:
`npx changelogen  --bump --premajor=beta`
