### ISSUE TITLE
How to cooperate with Bump and Changelogen?

### ISSUE THREAD

**Issue by djkloop** [unjs/changelogen#212]
### Describe the feature

I am using Bump to play the version number for my project, but I also need to build Changelog. How do I let Changelogen use the version number after Bumpp? Instead of the version number of Changelogen?

![image](https://github.com/user-attachments/assets/344b430a-0b11-415a-a996-158a299e51bd)

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by litingyes** [comment]
You can get the version in the current package.json through the variable `$npm_package_version`, so try `changeloggen -r $npm_package_version --output`

**Comment by pi0** [comment]
Changelog will be generated from a range of commits. For most control if you find a way to access those (or the tags associated with last release and next) you can use `--from`, `--to`. 

BTW changelogen is designed to **generate** next semantic version from the changelog not the other way around and it has override `-r <version>`/`--minor`/`--major`/`--patch`.
