### ISSUE TITLE
Remove Special Handling for Versions Starting with `0`

### ISSUE THREAD

**Issue by mrp-78** [unjs/changelogen#213]
### Environment

Node.js: v16.20.2
changelogen: latest

### Reproduction

https://github.com/mrp-78/changelogen

### Describe the bug

Currently, the repository includes a special case in its semantic versioning logic that treats versions starting with `0` differently. Specifically, it downgrades the semantic version increments as follows:
- **Major** versions are treated as **Minor**.
- **Minor** versions are treated as **Patch**.

This behavior deviates from the standard semantic versioning (SemVer) specification and can lead to unexpected results when generating changelogs or managing versioning across projects.

#### Reasons for Change
1. **Compliance with SemVer**: According to the [Semantic Versioning specification](https://semver.org/), versions starting with `0` are considered pre-release versions, but the increment rules (major, minor, patch) should still be respected as defined. The current logic overrides these rules, which can lead to confusion and inconsistency.

2. **Consistency Across Projects**: Many projects rely on tools that adhere strictly to SemVer. The special case handling in this repository can create discrepancies when integrating with other tools and systems, leading to potential issues in CI/CD pipelines, dependency management, and release strategies.

3. **Predictability**: Removing this special case will make the versioning behavior more predictable and transparent to users. This is crucial for maintaining trust in the tooling and for ensuring that versions convey the intended significance of changes.

#### Proposed Solution
I propose removing the special handling logic for versions starting with `0`, allowing the versioning to follow the standard SemVer rules. This will ensure that:
- Major versions remain major, even when starting with `0`.
- Minor versions remain minor, and patches remain patches, irrespective of the initial digit.

**Comment by pi0** [comment]
When the first digit is zero, the second means major, and the last minor or patch.

This condition is both specified in the standard that you linked and respected package managers (the second digit is major when the first is zero)

If this exception seems strange to you, i would suggest starting from `1.0.0` for more clarity, regardless it is how it is.

<img width="741" alt="image" src="https://github.com/user-attachments/assets/2babf9f8-2e91-47d3-bf44-844cc3d7cb4e">

**Comment by mrp-78** [comment]
My understanding of the Semantic Versioning document doesn't align with the idea that the second digit should be treated as the major version when the first digit is zero. 
One concern with this logic is that it would prevent me from easily bumping the package version from `0.y.z` to `1.0.0` using the arguments of the changelogen package.

**Comment by pi0** [comment]
`0.x` versioning conventionally works this way. package managers and library authors also follow this and the standard allows it. Again, it is how it is. From semver docs:

> Caret ranges are ideal when an author may make breaking changes between 0.2.4 and 0.3.0 releases, which is a common practice. However, it presumes that there will not be breaking changes between 0.2.4 and 0.2.5. It allows for changes that are presumed to be additive (but non-breaking), according to commonly observed practices.

> One concern with this logic is that it would prevent me from easily bumping the package version from 0.y.z to 1.0.0 using the arguments of the changelogen package.

You can use `-r 1.0.0` to declare package is going to bump from development into stable release. changelog en respects common practice for semver versioning and by doing this, it avoids accidentally bumping a package from development (`0.x`) into stable (`1.x`) simply if it sees a breaking change in commit history.
