### ISSUE TITLE
Does --minor --major --patch flags works right? 

### ISSUE THREAD

**Issue by kwangsing3** [unjs/changelogen#244]
### Environment

version: 0.5.7

### Reproduction

```npx changelogen@latest  --minor```
``` npx changelogen@latest --bump --patch```

### Describe the bug

It seems Semantic Versioning does not work as expected ? 

![螢幕擷取畫面 2024-11-20 151701](https://github.com/user-attachments/assets/b96da7eb-1e55-48ea-84cd-8ba99ac86efa)

### Additional context

![螢幕擷取畫面 2024-11-20 152936](https://github.com/user-attachments/assets/a9c48a38-1311-41d8-b26b-4ecce76d516d)

**Comment by pi0** [comment]
when first and second digit are zero, the semantics changes (second or third become major) -- this is according to npm docs. if you need major/minor/patch please start versions from 1.0.0
