### ISSUE TITLE
npx: package borked? 🤔

### ISSUE THREAD

**Issue by swand0g** [unjs/changelogen#5]
Just tried using `changelogen` with npx and I keep getting this error:
> /bin/env: bad interpreter: No such file or directory

I've tried on a couple different computers and seems to be happening whenever you try to run the script 🤔 (I am on node 16, btw)

**Comment by zhouweipeng** [comment]
I also encountered this problem, I am on node 14, btw

**Comment by pi0** [comment]
Thanks for the notice. It should be fixed in latest release (try with `npx changelogen@latest`)

**Comment by swand0g** [comment]
working now!
