### ISSUE TITLE
CHANGELOG.md file is not commited during the first release

### ISSUE THREAD

**Issue by sumerokr** [unjs/changelogen#60]
### Environment

OS: Ubuntu 22.04.1 LTS
node: 16.19.0
npm: 8.9.13
changelogen: latest (0.4.1)

### Reproduction

https://github.com/sumerokr/changelogen-reproduction

### Describe the bug

Dear UnJS team,
I have noticed that the first run of the `npx changelogen --release` command does not include the CHANGELOG.md file into the version bump commit. Is this on purpose?

### Logs

```sh
> git log
feat: init

> git status
nothing to commit, working tree clean

> npx changelogen --release

> git log
chore(release): v1.1.0
feat: init

> git status
Untracked files:
  CHANGELOG.md
```

**Comment by pi0** [comment]
Should be fixed by #64 (please ping to reopen if not 🙏🏼 )
