### ISSUE TITLE
support including handles of contributors

### ISSUE THREAD

**Issue by danielroe** [unjs/changelogen#63]
### Describe the feature

GitHub Releases marks contributors to releases by usage of @ handle. It would be nice to generate these in the contributors list at the bottom (maybe instead of email addresses) so they show up when the release is published.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by dnldsht** [comment]
Hi @danielroe, it is supposed to work like that but the service that retrive github usernames from email address has changed. 

In pull request #55 I've fixed that, you can merge this [commit](https://github.com/unjs/changelogen/pull/55/commits/ab1e587d334615a75196c0a0974ea9caef2d2697) or I can make a PR that only fix that.

**Comment by pi0** [comment]
Another note that, it works only if commit email matches a **public account**.

**Comment by pi0** [comment]
Thanks for the notice @dnldsht. I have added backward compatibility route to ungh until updating changlogen (https://github.com/unjs/ungh/commit/6178c4aca0b8281a70dc7d54cb90a2b18de56d7a)  (https://ungh.cc/users/find/pooya@pi0.io)
