### ISSUE TITLE
Could we extract the bump function?

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/changelogen#66]
Hello,

Actually, I'm using [codacy/git-version](https://github.com/codacy/git-version) but it use a dev and a main branch which is really annoying. So, I'm looking for a way to generate the next version using conventional commit. I'm not founding anything but looking at this package, I think that it could be awesome to extract the bump function into it's own package to be able to generate, using lastest tag and last commits a new version without the pain of the dev and main branch.

Then, in this package, we could use the new package to get a version.

**Comment by pi0** [comment]
Hi dear @Barbapapazes. Happy you find it useful. Also it is a nice idea to only extract bump functionality. 

I myself use it for nitro-automated edge releases for example. Changelogen already exposes utilities you can import them programmatically from the package. Would that be useful to make it simpler `bumpVersion` utility exposed?

**Comment by Barbapapazes** [comment]
Okk, I didn't know that changelogen expose this utility. I will try it. 

But it could be useful to add documentation about these functions that are exposed.

**Comment by Barbapapazes** [comment]
And I'm thinking about building a GitHub action for it.

**Comment by Barbapapazes** [comment]
To explain more, I'm working on project where there is not necessary a package.json or a CHANGELOG but where we need to easily get a new semver version using commits from the lastest tag. And I think that this package have all I want to do but automatic bump of changelog generation is not something I need.

**Comment by Barbapapazes** [comment]
Hello @pi0,

After deep diving in the code, I understand that the function `bumpVersion` update the package json file. So that not exactly what I needed. But anyway, I succeeded to write my script to generate a new version and the main function is `determineSemverChange`. I'm not sure what can be done but it seems that this package has much more power than juste update a `changelog.md` or a `package.json` file. Maybe more docs could show that.

My script: https://github.com/aneoconsulting/ArmoniK.Api/pull/185/files#diff-6e31c0ba82d99f48d77e556e24cbf18d8b2ed1757a2eef7b61085368019f689d

**Comment by Barbapapazes** [comment]
Done, will close this issue but I'm convinced that a docs could help!

**Comment by Barbapapazes** [comment]
Done, will close this issue but I'm convainced th
